# Numpy: Arrays y Vectorización

## 0. Prerrequisitos

Para correr este notebook, deben asegurarse de haber creado el virtual environment the python siguiendo las instrucciones del README. Una vez creado, selecciona el kernel del notebook.

Para instalar python, el manejador de paquets UV, los ambientes de conda y configurar Visual Studio Code para correr y editar Jupyter Notebooks en él, revisen los siguientes recursos:


- [Cómo instalar Conda](https://youtu.be/TJor7z8g8FA?si=7-VUSQJiew6Hu_gW)
- [Instalación de UV](https://youtu.be/YzOLOlH1jQk?si=2hFk6aAh8gCoMvuo)
- [VS Code + Jupyter Notebooks](https://youtu.be/rL1usXq4bgE?si=2b5REnUzVBMDxWfF)

## 1. Crear Arrays

### 1.1 A partir de listas

Primero, importaremos la librería `numpy` que es con la que vamos a desarrollar todo este notebook.

In [29]:
import numpy as np

Los arrays de NumPy son estructuras de datos optimizadas que permiten operaciones matemáticas rápidas sobre listas, haciéndolas más eficientes en memoria y velocidad que los loops de Python puro. Además, mediante la utilización de estos arrays podemos hacer representaciones de estructuras de varias dimensiones como vectores, matrices o tensores, y realizar operaciones matemáticas con ellas. (Si quieren conocer sobre estas estructuras y cómo se hacen operaciones entre ellas, recomiendo ver el canal **1a con Berni** en su playlist de [Álgebra lineal](https://youtube.com/playlist?list=PLCY1BPxILEJXqCFAmhXxrMYFk8mEhDkzo&si=sWEugwYgIHI1xtS4).

In [30]:
# Vector de una dimensión

vector_1d = np.array([1,2,3,4,5])

vector_1d

array([1, 2, 3, 4, 5])

In [31]:
# Matrix 2 x 3

matrix_2x3 = np.array([[1,2,3],[4,5,6]])
matrix_2x3

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# Tensor 3 x 2 x 2

tensor_3x2x2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
tensor_3x2x2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

Todos estas estructuras están bajo el mismo tipo de dato `array` de numpy. Para poder acceder a sus datos internos el procedimiento es similar a como se hace con listas, utilizamos indexación de 0 a 1 en cada una de las dimensiones de la estructura.

In [33]:
print("La dimensión del vector es:", vector_1d.ndim)
print("Su elemento en la posición 2 es:", vector_1d[1])

La dimensión del vector es: 1
Su elemento en la posición 2 es: 2


In [34]:
print("La dimensión de la matrix es:", matrix_2x3.ndim)
print("Su elemento en la posición (1,2) es:", matrix_2x3[1,2])

La dimensión de la matrix es: 2
Su elemento en la posición (1,2) es: 6


In [35]:
print("La dimensión del tensor es:", tensor_3x2x2.ndim)
print("Su elemento en la posición (1,0,1) es:", tensor_3x2x2[1,0,1])

La dimensión del tensor es: 3
Su elemento en la posición (1,0,1) es: 6


Así mismo, al igual que con las listas, podemos cambiar los valores de un array conociendo su posición en la lista.

In [36]:
print("El elemento del tensor en la posición (1,0,1) es:", tensor_3x2x2[1,0,1])

tensor_3x2x2[1,0,1] = 100

print("El elemento del tensor en la posición (1,0,1) es:", tensor_3x2x2[1,0,1])

El elemento del tensor en la posición (1,0,1) es: 6
El elemento del tensor en la posición (1,0,1) es: 100


También mediante indexing puedes acceder a varios valores de un mismo array y obtener un subarray.

In [45]:
tensor_3x2x2[1,0:2,1]

array([100,   8])

**Profundiza más**

Si quieres ir más allá, pregunta a tu IA de confianza:

- `¿Cuál es la diferencia entre un list de Python y un array de NumPy en términos de memoria y velocidad?`
- `¿Cómo funciona el indexing en arrays multidimensionales y cómo accedo a subarrays (slicing)?`
- `¿Qué es el atributo dtype en arrays y por qué importa para operaciones matemáticas?`
- `¿Qué pasa en NumPy cuando asigno un array a otra variable sin usar .copy()? ¿Por qué es importante hacer copias explícitas de arrays?`

### 1.2 Con ceros o valores vacíos

Supongamos que queremos crear un array en el que vamos a guardar los datos de algún cálculo en cada posición del array, pero ese array es de $1000 \times 1000$ valores, es decir, una matrix de $1000 \times 1000$. Hacer esto a partir de una lista implicaría que tendríamos que escribir a mano todos los arrays para tener $1 \times 10^6$ números, lo cual no tiene ningún sentido práctico. Es por ello que numpy permite crear arrays con valores predeterminados.

In [37]:
# Array de ceros
array_zeros = np.zeros((2,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# Array de unos
array_ones = np.ones((3,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
# Array de números aleatorios
array_random = np.random.rand(2,3)
array_random

array([[0.7723247 , 0.69172639, 0.31977642],
       [0.80184741, 0.87763734, 0.09129848]])

In [40]:
# Array de elementos vacíos
array_empty = np.empty((2,3))
array_empty

array([[0.7723247 , 0.69172639, 0.31977642],
       [0.80184741, 0.87763734, 0.09129848]])

Esa es la manera de crear arrays para cualquier tipo de dimensión. Sin embargo, hay arrays que son útiles en dimensiones específicas, por ejemplo, para una dimensión, son muy utilizados los arrays creados por 

- `np.linspace` : Crea un array unidimensional que indica un valor inicial y un valor final y cuantos puntos equidistantes quieres que haya entre esos dos valores incluyendo el valor del final.
- `np.arange`: Crear un array unidimensional que genera valores desde un inicio hasta un final, incrementando de a un paso específico.

In [41]:
array_npuntos = np.linspace(0, 10, 5)
array_npuntos

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
array_xpaso = np.arange(0, 10, 2)
array_xpaso

array([0, 2, 4, 6, 8])

**Profundiza más**

Si quieres ir más allá, pregunta a tu IA de confianza:

- `¿Cuál es la diferencia entre np.linspace() y np.arange() y cuándo debo usar cada una?`
- `¿Qué otras funciones de NumPy existen para crear arrays especiales (np.eye(), np.diag(), np.full())?`
- `¿Cómo controlo la aleatoriedad en np.random.rand() usando seeds?`


## 2. Propiedades de los Arrays